name: Check VERSION Changed in PR to Main

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  check-version-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get VERSION from PR branch (head)
        id: pr_version
        run: |
          PR_VERSION=$(cat VERSION)
          echo "pr_version=$PR_VERSION" >> $GITHUB_OUTPUT

      - name: Get VERSION from main branch (base)
        id: base_version
        run: |
          git fetch origin main
          BASE_VERSION=$(git show origin/main:VERSION)
          echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT

      - name: Compare VERSION files
        run: |
          echo "Base (main) VERSION: ${{ steps.base_version.outputs.base_version }}"
          echo "PR    (head) VERSION: ${{ steps.pr_version.outputs.pr_version }}"
          if [ "${{ steps.base_version.outputs.base_version }}" = "${{ steps.pr_version.outputs.pr_version }}" ]; then
            echo "❌ The VERSION file did not change. It must be updated to reflect a new release version."
            exit 1
          else
            echo "✅ The VERSION file changed correctly."
          fi
